name: ContinuousIntegration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  linux:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: sudo apt update && sudo apt -y install libsodium-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSOLANACEAE_ECOSYSTEM_BUILD_TESTING=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 4

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

  android:
    timeout-minutes: 30
    # contains sections copied from sdl repo

    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - vcpkg_toolkit: arm-neon-android
            ndk_abi: armeabi-v7a
          - vcpkg_toolkit: arm64-android
            ndk_abi: arm64-v8a
          - vcpkg_toolkit: x64-android
            ndk_abi: x86_64

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: nttld/setup-ndk@v1
      id: setup_ndk
      with:
        local-cache: false # https://github.com/nttld/setup-ndk/issues/518
        ndk-version: r26d

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Dependencies (host)
      run: sudo apt update && sudo apt -y install cmake pkg-config nasm

    - name: Install Dependencies (target)
      env:
        ANDROID_NDK_HOME: ${{steps.setup_ndk.outputs.ndk-path}}
      #run: vcpkg install --triplet ${{matrix.platform.vcpkg_toolkit}} libsodium openssl opus libvpx libpng libjpeg-turbo
      run: vcpkg install --triplet ${{matrix.platform.vcpkg_toolkit}} libsodium openssl

    # vcpkg scripts root /usr/local/share/vcpkg/scripts
    - name: Configure CMake
      env:
        ANDROID_NDK_HOME: ${{steps.setup_ndk.outputs.ndk-path}}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${{matrix.platform.vcpkg_toolkit}} -DANDROID=1 -DANDROID_PLATFORM=23 -DANDROID_ABI=${{matrix.platform.ndk_abi}} -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${{steps.setup_ndk.outputs.ndk-path}}/build/cmake/android.toolchain.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 4

    - name: Compress artifacts
      shell: bash
      run: |
        tar -czvf ${{ github.event.repository.name }}-${{matrix.platform.vcpkg_toolkit}}.tar.gz -C ${{github.workspace}}/build/bin/ .

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{matrix.platform.vcpkg_toolkit}}
        # TODO: do propper packing
        path: |
          ${{github.workspace}}/${{github.event.repository.name}}-${{matrix.platform.vcpkg_toolkit}}.tar.gz

  macos:
    timeout-minutes: 10

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Dependencies
      run: brew install libsodium

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSOLANACEAE_ECOSYSTEM_BUILD_TESTING=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

  windows:
    timeout-minutes: 15

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Install Dependencies
      env:
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      run: vcpkg install pkgconf:x64-windows libsodium:x64-windows-static pthreads:x64-windows-static

    # setup vs env
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSOLANACEAE_ECOSYSTEM_BUILD_TESTING=ON -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DPKG_CONFIG_EXECUTABLE=C:/vcpkg/installed/x64-windows/tools/pkgconf/pkgconf.exe

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 3

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

